version: "3.9"
   
services:
  postgres_db:
    image: postgres:14.1
    container_name: amigoscode-postgres
    volumes:
      - amigoscode_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres
    # restart: "on-failure"
    ports:
      - "5500:5432"
volumes:
  amigoscode_postgres_data: